version: '3.7'
services:
  influxdb:
    image: "influxdb:1.8.4-alpine"
    hostname: "influxdb"
    container_name: influxdb
    ports: 
        - "8086:8086"
    networks:
        - vcctestnetwork
  chronograf:
    image: "chronograf:latest"
    hostname: "chronograf"
    container_name: chronograf
    ports: 
        - "8000:8888"
    networks:
        - vcctestnetwork
    volumes:
      - /home/umang/Desktop/M20CS017_M20CS020_VCCENDSEM/certificates:/mycertis
    environment:
      - TLS_CERTIFICATE=/mycertis/dipinticertificate.pem
      - TLS_PRIVATE_KEY=/mycertis/umangkey.pem
  telegraf:
    image: "telegraf:latest"
    hostname: "telegraf"
    container_name: telegraf
    networks:
        - vcctestnetwork
  kapacitor:
    image: "kapacitor:latest"
    hostname: "kapacitor"
    container_name: "kapacitor"
    environment: 
        - "KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086"
    ports:
        - "9092:9092"
    networks:
        - vcctestnetwork
networks:
    vcctestnetwork:
